# This is a basic workflow to help you get started with Actions

name: deploy-gh-pages
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: |
            dist
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: false # Automatically remove deleted files from the deploy branch
